spring:
  #单机方式
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 10.33.123.89 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    #    password: redis # Redis服务器连接密码（默认为空）
    timeout: 10000   # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 1024 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200 # 连接池中的最大空闲连接
        min-idle: 200 # 连接池中的最小空闲连接

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露端点